### ISSUE TITLE
Is it possible to batch send webpushes?

### ISSUE THREAD

**Issue by mgrzeszczak** [lahiiru/browser-push#4]
Say I have a million clients, do I have to call the endpoint for each of them separately? Surely there must be a way to do this sensibly.

**Comment by lahiiru** [comment]
No you can use batch mode

**Comment by lahiiru** [comment]
if you are going to use own backend, see this https://github.com/web-push-libs/web-push/issues/163

**Comment by mgrzeszczak** [comment]
OK the standard doesn't support this.
