### ISSUE TITLE
Doc fails to explain the mechanism properly.

### ISSUE THREAD

**Issue by gitcnd** [lahiiru/browser-push#6]
Awesome project - small problem:  The doc ( https://lahiiru.github.io/browser-push/ ) says:-

    " Those are delivered to a web browser.  "

Which is not a helpful thing in an explanation right after neatly explaining the other kind of push well (mobile apps).

Full context:

" **Mobile push notifications** can be sent from your back-end to some device owner’s notification service such as Google’s FCM or Apple’s APNS. Whenever the recipient device has the internet connectivity, **pending messages are fetched from device owner’s notification service and displayed to the user.** " - awesome!
" **Web push notifications** or browser push notifications are somewhat different. **Those are delivered to a web browser.** " - um, yeah, we know that - but **how** ?  Does the browser poll something looking for these?  What?  When?  How??

Thanks!

**Comment by lahiiru** [comment]
Thank you very much @gitcnd Chris Drake for your constructive feedback! I will correct the document. Before it please see the required explanation here.

> Does the browser poll something looking for these? What? When? How?

Web push notifications are first created at your application back-end and you post those to the browser owner's WebPush service (e.g. Google Chrome -> FCM). Then, these notifications are delivered to your application user's browser (the last destination); This communication happens over a WebSocket channel which is created by a browser ServiceWorker thread.

![image](https://user-images.githubusercontent.com/8580134/132126796-1e0c22e7-9abc-4084-9998-39ccc0581a5f.png)
More info: https://wiki.mozilla.org/Firefox/Push_Notifications

**Comment by gitcnd** [comment]
Thanks! I figured it must be something so "obvious" to people who know already that it got overlooked here ... and as it turns out it's the same as mobile push, right?  Does Safari use APNS as well? (Yes, I'm aware Safari use a different protocol)

The Firefox digram you include says "send endpoint" in step 2... does that mean the the *browser* tells my *server* the destination that it wants my server to (later( deliver the push messages to?   Do they happen to all be the same, or does each browser maker run their own push socket server for us?

**Comment by lahiiru** [comment]
> it's the same as mobile push, right?

**Yes,**

> Does Safari use APNS as well?

**Yes, see below,**
![image](https://user-images.githubusercontent.com/8580134/132128787-7111f438-191f-426e-a78f-4fb4a0ec7629.png)

> does that mean the browser tells my server the destination that it wants my server to (later( deliver the push messages to?

**Yes**

When our web application (Javascript code) does the `pushManager.subscribe()`, Browser creates a `PushSubcription` with the help of its browser back-end services like below (Burps capture). You can see the `PushSubcription` object in the response. In the Firefox diagram, (2) send endpoint means sending this whole `PushSubcription` object (it includes the endpoint as you told) to your application back-end.

![image](https://user-images.githubusercontent.com/8580134/132129215-b9fbda5f-43d9-4d13-86c2-009a56cb1d00.png)

> Do they happen to all be the same, or does each browser maker run their own push socket server for us?

**See the `PushSubcription` of different browsers (Burp capture is from Chrome). You will figure out the answer**

- Opera
   ![image](https://user-images.githubusercontent.com/8580134/132129757-c1f15362-8d6e-4e37-88f0-1d73156b2146.png)
- Firefox
  ![image](https://user-images.githubusercontent.com/8580134/132129814-1b48b5b0-e886-4df2-9ffa-21dfad74111b.png)

**Comment by lahiiru** [comment]
@gitcnd Chris Drake, hope you are fine with the details; feel free to open if you have any.
